- hosts: all
  become: true
  tasks:
      # for Ubuntu
      - name: Install apache and php for Ubuntu servers
        apt:
            name:
                - apache2
                - libapache2-mod-php
            state: latest
            update_cache: true
        when: ansible_distribution == "Ubuntu"
      # dor CentOS
      - name: Add PHP support for apache
        apt:
            name:
                - httpd
                - php
            state: latest
            update_cache: true
        when: ansible_distribution == "CentOS"
