- hosts: all
  become: true
  tasks:
      - name: Ping check hosts
        ping: ~
      - name: Update repository index
        apt:
            update_cache: yes
      - name: Uninstall apache2 package
        apt:
            name: apache2
            state: absent
      - name: Remove add PHP support for apache
        apt:
            name: libapache2-mod-php
            state: absent
