- hosts: all
  become: true
  tasks:
      - name: Install updates(CentOS)
        tags: always
        dnf:
            update_only: true
            update_cache: true
        when: ansible_distribution == "CentOS"

      - name: Install updates(Ubuntu)
        tags: always
        dnf:
            upgrade: dist
            update_cache: true
        when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
      # for Ubuntu
      - name: Install apache and php for Ubuntu servers
        tags: apache, apache2, ubuntu
        apt:
            name:
                - apache2
                - libapache2-mod-php
            state: latest
            update_cache: true
        when: ansible_distribution == "Ubuntu"
      # for CentOS
      - name: Add PHP support for apache
        tags: apache, httpd, centos
        apt:
            name:
                - httpd
                - php
            state: latest
            update_cache: true
        when: ansible_distribution == "CentOS"
      # copy file
      - name: Copy default html file for site
        tags: apache, apache2, httpd
        copy:
            src: default_site.html
            dest: /var/www/html/index.html
            owner: root
            group: root
            mode: 0644
      #
      - name: Start httpd (CentOS)
        tags: apache, centos, httpd
        service:
            name: httpd
            state: started
            enable: yes
        when: ansible_distribution == "CentOS"
      - name: Change email address for Admin
        tags: apache, centos,httpd
        lineinfile:
            path: /etc/httpd/conf/httpd.conf
            regexp: '^ServerAdmin'
            line: ServerAdmin somebody@somewhere.net
        when: ansible_distribution == "CentOS"
        register: httpd 
      - name: restart httpd (CentOS)
        tags: apache, centos, httpd
        service:
            name: httpd
            state: restarted
        when: httpd.changed

- hosts: db_servers
  become: true
  tasks:
      # for Ubuntu
      - name: Install mariadb for Ubuntu servers
        tags: ubuntu, db, mariadb
        apt:
            name:
                - mariadb-server
            state: latest
        when: ansible_distribution == "Ubuntu"
      # for CentOS
      - name: Install mariadb for CentOS server
        tags: centos, db, mariadb
        apt:
            name:
                - mariadb
            state: latest
        when: ansible_distribution == "CentOS"

- host: workstations
  become: true
  tasks:
      - name: Install unzip
        package:
            name: unzip
      - name: Install terraform
        unarchive:
            src: https://
            dest: /usr/local/bin
            remote_src: yes
            mode: 0755
            owner: root
            group: root
