- hosts: all
  become: true
  tasks:
      - name: Install updates(CentOS)
        tags: always
        dnf:
            update_only: true
            update_cache: true
        when: ansible_distribution == "CentOS"

      - name: Install updates(Ubuntu)
        tags: always
        dnf:
            upgrade: dist
            update_cache: true
        when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
      # for Ubuntu
      - name: Install apache and php for Ubuntu servers
        tags: apache, apache2, ubuntu
        apt:
            name:
                - apache2
                - libapache2-mod-php
            state: latest
            update_cache: true
        when: ansible_distribution == "Ubuntu"
      # for CentOS
      - name: Add PHP support for apache
        tags: apache, httpd, centos
        apt:
            name:
                - httpd
                - php
            state: latest
            update_cache: true
        when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
      # for Ubuntu
      - name: Install mariadb for Ubuntu servers
        tags: ubuntu, db, mariadb
        apt:
            name:
                - mariadb-server
            state: latest
        when: ansible_distribution == "Ubuntu"
      # for CentOS
      - name: Install mariadb for CentOS server
        tags: centos, db, mariadb
        apt:
            name:
                - mariadb
            state: latest
        when: ansible_distribution == "CentOS"
