---
- name: Deploy Chatwoot using Docker Compose
  hosts: all
  become: no
  vars_files:
    - ../external_vars.yaml

  tasks:
    - name: Create Chatwoot directory
      file:
        path: '{{ chatwoot_dir }}'
        state: directory

    - name: Download .env template
      get_url:
        url: '{{ chatwoot_env_url }}'
        dest: '{{ chatwoot_dir }}/.env'

    - name: Download Docker Compose template
      get_url:
        url: '{{ chatwoot_docker_compose_url }}'
        dest: '{{ chatwoot_dir }}/docker-compose.yaml'

    - name: Update .env file
      lineinfile:
        path: '{{ chatwoot_dir }}/.env'
        regexp: '^(REDIS_PASSWORD=|# POSTGRES_DATABASE=|FRONTEND_URL=http://0.0.0.0:3000)'
        line: '{{ item }}'
      loop:
        - 'REDIS_PASSWORD='
        - 'POSTGRES_PASSWORD={{ chatwoot_db_password }}'
        - 'FRONTEND_URL={{chatwoot_url}}'

    - name: Update docker-compose.yaml file for PostgreSQL password
      replace:
        path: '{{ chatwoot_dir }}/docker-compose.yaml'
        regexp: 'POSTGRES_PASSWORD=.*'
        replace: 'POSTGRES_PASSWORD={{chatwoot_db_password }}'

    - name: Prepare the database by running migrations
      command: docker compose run --rm rails bundle exec rails db:chatwoot_prepare
      args:
        chdir: '{{ chatwoot_dir }}'

    - name: Start Chatwoot using Docker Compose
      command: docker compose up -d
      args:
        chdir: '{{ chatwoot_dir }}'
