- name: Install & Secure MySQL 8.0.28 on Ubuntu
  hosts: ubuntu_servers
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add MySQL APT Repository Key
      apt_key:
        url: https://dev.mysql.com/get/mysql-apt-config_0.8.17-1_all.deb
        state: present

    - name: Install MySQL APT Repository
      apt_repository:
        repo: 'deb http://repo.mysql.com/apt/ubuntu/ {{ ansible_distribution_release }} mysql-8.0'
        state: present

    - name: Install MySQL 8.0.28 packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - mysql-server=8.0.28-1ubuntu20.04
        - mysql-client=8.0.28-1ubuntu20.04
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set root user password
      mysql_user:
        name: root
        password: '{{ root_password }}'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host: localhost
        login_user: root
        login_password: ''
        state: present

    - name: Create admin user with remote access
      mysql_user:
        name: '{{ admin_user }}'
        password: '{{ admin_password }}'
        priv: '*.*:ALL'
        host: '%'
        append_privs: yes
        login_user: root
        login_password: '{{ root_password }}'
        state: present

    - name: Create database
      mysql_db:
        name: '{{ db_name }}'
        state: present
        login_user: root
        login_password: '{{ root_password }}'

    - name: Enable remote login to MySQL
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regex: '^bind-address\s*=\s*127.0.0.1'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart MySQL

    - name: Execute MySQL secure installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter password for user root:': '{{ root_password }}'
          'Press y\|Y for Yes, any other key for No': 'Y'
          'Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG': '{{ password_validation_policy }}'
          'Change the password for root \? \(\(Press y\|Y for Yes, any other key for No\)': 'n'
          'Remove anonymous users\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Disallow root login remotely\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Remove test database and access to it\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Reload privilege tables now\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
      environment:
        MYSQL_PWD: '{{ root_password }}'

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
