---
- name: Install Mysql on Ubuntu
  hosts: all
  become: true

  vars_files:
    - ./vars/external_vars.yaml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installing Mysql
      package:
        name: '{{item}}'
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Check if root password is already set
      shell: >
        mysql -uroot -p'{{ mysql_root_password }}' -e "SELECT 1;"
      register: mysql_root_password_check
      ignore_errors: yes

    - name: Set root user password
      mysql_user:
        name: root
        password: '{{ mysql_root_password }}'
        # login_unix_socket: /var/run/mysqld/mysqld.sock
        host: localhost
        login_user: root
        login_password: ''
        state: present
      when: mysql_root_password_check.failed

    - name: creating database
      mysql_db:
        name: '{{ mysql_db_name }}'
        state: present
        login_user: root
        login_password: '{{ mysql_root_password }}'

    - name: Create admin user with remote access
      mysql_user:
        name: '{{ mysql_admin_user }}'
        password: '{{ mysql_admin_password }}'
        priv: '{{ mysql_db_name }}.*:ALL'
        host: 'localhost'
        append_privs: yes
        login_user: root
        login_password: '{{ mysql_root_password }}'
        state: present
        
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
