---
- name: Install Mysql on Ubuntu
  hosts: all
  become: true

  vars_files:
    - ./vars/external_vars.yaml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installing Mysql
      package:
        name: '{{item}}'
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes

    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Check if root password is already set
      shell: >
        mysql -uroot -p'{{ mysql_root_password }}' -e "SELECT 1;"
      register: mysql_root_password_check
      ignore_errors: yes

    - name: Set root user password
      mysql_user:
        name: root
        password: '{{ mysql_root_password }}'
        # login_unix_socket: /var/run/mysqld/mysqld.sock
        host: localhost
        login_user: root
        login_password: ''
        state: present
      when: mysql_root_password_check.failed

    - name: creating database
      mysql_db:
        name: '{{ mysql_db_name }}'
        state: present
        login_user: root
        login_password: '{{ mysql_root_password }}'

    - name: Create admin user with remote access
      mysql_user:
        name: '{{ mysql_admin_user }}'
        password: '{{ mysql_admin_password }}'
        priv: '{{ mysql_db_name }}.*:ALL'
        host: 'localhost'
        append_privs: yes
        login_user: root
        login_password: '{{ mysql_root_password }}'
        state: present

  #   - name: Enable remote login to mysql
  #     lineinfile:
  #       path: /etc/mysql/mysql.conf.d/mysqld.cnf
  #       regex: '^bind-address\s*=\s*127.0.0.1'
  #       line: 'bind-address = 0.0.0.0'
  #       backup: yes
  #     notify:
  #       - Restart mysql

  #   - name: Execute MySQL secure installation
  #     expect:
  #       command: mysql_secure_installation
  #       responses:
  #         'Enter password for user root:': '{{ root_password }}'
  #         'Press y\|Y for Yes, any other key for No': 'Y'
  #         'Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG': '{{ password_validation_policy }}'
  #         'Change the password for root \? \(\(Press y\|Y for Yes, any other key for No\)': 'n'
  #         'Remove anonymous users\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
  #         'Disallow root login remotely\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
  #         'Remove test database and access to it\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
  #         'Reload privilege tables now\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
  #     environment:
  #       MYSQL_PWD: '{{ root_password }}'

  # handlers:
  #   - name: Restart mysql
  #     service:
  #       name: mysql
  #       state: restarted
