---
- name: Install PostgreSQL 14 on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Add PostgreSQL APT repository
      shell: |
        echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

    - name: Add PostgreSQL repository key
      shell: |
        wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null

    - name: Update APT package list
      apt:
        update_cache: yes
