---
- name: Install PostgreSQL on Ubuntu
  hosts: all
  become: yes
  vars_files:
    - ../external_vars.yaml
  tasks:
    - name: Ensure curl and ca-certificates are installed
      apt:
        name:
          - curl
          - ca-certificates
        state: present

    - name: Create directory for PostgreSQL key
      file:
        path: /usr/share/postgresql-common/pgdg
        state: directory
        mode: '0755'

    - name: Download PostgreSQL key
      get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc

    - name: Check if PostgreSQL APT repository is already added
      stat:
        path: /etc/apt/sources.list.d/pgdg.list
      register: pgdg_repo

    - name: Add PostgreSQL APT repository
      shell: |
        echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
      changed_when: true

    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: python3-psycopg2
        state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql-{{postgresql_version}}
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Ensure PostgreSQL is started and enabled
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Set password for postgres user
      become: yes
      become_method: sudo
      become_user: '{{ postgresql_root_user }}'
      postgresql_user:
        db: postgres
        name: '{{ postgresql_root_user }}'
        password: '{{ postgresql_root_password }}'
    - name: Ensure PostgreSQL pg_hba.conf has the correct authentication line
      lineinfile:
        path: '/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf'
        regexp: '^local\s+all\s+postgres\s+'
        line: 'local   all             postgres                                md5'
        state: present
      notify:
        - Restart PostgreSQL

    - name: Create a new database
      postgresql_db:
        name: '{{ postgresql_db_name }}'
        state: present
        login_host: '{{ postgresql_host }}'
        login_port: '{{ postgresql_port }}'
        login_user: '{{ postgresql_root_user }}'
        login_password: '{{ postgresql_root_password }}'

    - name: Create a new admin user
      postgresql_user:
        name: '{{ postgresql_admin_user }}'
        password: '{{ postgresql_admin_password }}'
        role_attr_flags: CREATEDB,CREATEROLE,LOGIN
        login_host: '{{ postgresql_host }}'
        login_port: '{{ postgresql_port }}'
        login_user: '{{ postgresql_root_user }}'
        login_password: '{{ postgresql_root_password }}'

    - name: Grant all privileges on all databases to the admin user
      postgresql_privs:
        database: '{{ postgresql_db_name }}'
        state: present
        privs: ALL
        type: database
        role: '{{ postgresql_admin_user }}'
        login_host: '{{ postgresql_host }}'
        login_port: '{{ postgresql_port }}'
        login_user: '{{ postgresql_root_user }}'
        login_password: '{{ postgresql_root_password }}'

    - name: Grant all privileges on schema public to the admin user
      postgresql_privs:
        database: '{{ postgresql_db_name }}'
        state: present
        privs: ALL
        type: schema
        objs: 'public'
        role: '{{ postgresql_admin_user }}'
        login_host: '{{ postgresql_host }}'
        login_port: '{{ postgresql_port }}'
        login_user: '{{ postgresql_root_user }}'
        login_password: '{{ postgresql_root_password }}'
  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted
