---
- name: Check if PostgreSQL root password is set
  hosts: all
  become: yes
  tasks:
    - name: Change PostgreSQL user password
      postgresql_user:
        name: postgres
        password: '{{ new_postgres_password }}'
        state: present
      vars:
        new_postgres_password: 'new_secure_password'
