---
- name: test
  hosts: all
  become: yes
  vars_files:
    - ./vars/external_vars.yaml
  tasks:
    - name: Grant usage on schema public to the admin user
      postgresql_privs:
        database: '{{ postgresql_db_name }}'
        state: present
        privs: USAGE
        type: schema
        schema: public
        role: '{{ postgresql_admin_user }}'
        login_host: '{{ postgresql_host }}'
        login_port: '{{ postgresql_port }}'
        login_user: '{{ postgresql_root_user }}'
        login_password: '{{ postgresql_root_password }}'

    - name: Grant all privileges on schema public to the admin user
      postgresql_privs:
        database: '{{ postgresql_db_name }}'
        state: present
        privs: ALL
        type: schema
        schema: public
        role: '{{ postgresql_admin_user }}'
        login_host: '{{ postgresql_host }}'
        login_port: '{{ postgresql_port }}'
        login_user: '{{ postgresql_root_user }}'
        login_password: '{{ postgresql_root_password }}'
