---
- name: Change PostgreSQL Password
  hosts: all
  become: yes
  tasks:
    - name: Change PostgreSQL password
      shell: |
        psql -c "ALTER USER postgres WITH PASSWORD '{{ new_postgres_password }}';"
      vars:
        new_postgres_password: 'secret'
      become_user: postgres
