---
- name: Deploy React.js Application
  hosts: all
  become: no
  vars_files:
    - ../../external_vars.yaml

  tasks:
    - name: Run ssh-keyscan to add GitLab to known_hosts
      shell: ssh-keyscan gitlab.lisod.vn >> ~/.ssh/known_hosts
      args:
        creates: ~/.ssh/known_hosts

    - name: Check if local React.js directory exists
      stat:
        path: '{{ reactjs_project_local_path }}'
      register: local_reactjs_exists

    - name: Exit playbook if local React.js already exists
      meta: end_play
      when: local_reactjs_exists.stat.exists

    - name: Clone the React.js project repository
      git:
        repo: '{{ reactjs_git_repo }}'
        dest: '{{ reactjs_project_local_path }}'
        update: yes

    - name: Copy React.js from local directory
      command: cp -ra {{ reactjs_project_local_path }} {{ reactjs_project_path }}
      become: yes

    - name: Ensure NVM is loaded and install yarn
      shell: |
        bash -i -c 'yarn'
      args:
        chdir: '{{ reactjs_project_path }}'
      environment:
        HOME: /home/{{server_user}}

    - name: Copy environment file
      copy:
        src: '{{ reactjs_project_path }}/{{ reactjs_env_file }}'
        dest: '{{ reactjs_project_path }}/{{ reactjs_env_destination }}'
        remote_src: yes

    - name: Build the React.js application
      shell: |
        bash -i -c 'yarn build'
      args:
        chdir: '{{ reactjs_project_path }}'

    # Run pm2
    - name: Ensure pm2-configs directory exists
      file:
        path: /home/{{ server_user }}/pm2-configs
        state: directory

    - name: Copy pm2-react.json to the server
      copy:
        src: ../configs/pm2/pm2-react.json
        dest: /home/{{ server_user }}/pm2-configs/pm2-react.json

    - name: Start react.js app with PM2
      shell: |
        bash -i -c 'pm2 start /home/{{ server_user }}/pm2-configs/pm2-react.json'

    - name: Save the PM2 process list
      shell: |
        bash -i -c ' env PATH=$PATH:/home/{{server_user}}/.nvm/versions/node/{{node_version}}/bin /home/{{server_user}}/.nvm/versions/node/{{node_version}}/lib/node_modules/pm2/bin/pm2 startup systemd -u {{server_user}} --hp /home/{{server_user}}'
      become: true

    - name: Save the PM2 process list
      shell: |
        bash -i -c 'pm2 save'
